<template>
    <div class="main">
        <carousel />
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
        <h2>avc</h2>
    </div>

   
</template>
<script setup lang="ts">
import carousel from '~/components/carousel.vue';
</script>